## Stage 1 : build with maven builder image
FROM node:14-alpine AS build
WORKDIR /usr/src/app
COPY package.json yarn.lock .
RUN yarn --frozen-lockfile
COPY public ./public
COPY tsconfig.json .
COPY src ./src
RUN yarn build --frozen-lockfile

## Stage 2 : create the docker final image
FROM registry.access.redhat.com/ubi8/nginx-118
ENV LANG=en_US.utf8

COPY nginx/nginx.conf "${NGINX_CONF_PATH}"
COPY --from=build usr/src/app/build/ /var/www

EXPOSE 8080/tcp

CMD nginx -g "daemon off;"

