#!/usr/bin/env bash
set -e

## Testing using quarkus snapshot + no real platform; just core. Will thus not find platform issues; but will
## find core vs code.quarkus issues.
cd api && mvn --settings ../.github/quarkus-ecosystem-maven-settings.xml -B clean install \
    -Dquarkus.devtools.version=${QUARKUS_VERSION}  \
    -Dquarkus.platform.group-id=io.quarkus \
    -Dquarkus.platform.artifact-id=quarkus-bom \
    -Dquarkus.platform.version=${QUARKUS_VERSION}
