package io.quarkus.code.github

import io.quarkus.code.github.model.CreatedRepository
import io.quarkus.code.github.model.TokenParameter
import io.quarkus.code.github.model.TokenResponse
import org.eclipse.jgit.api.Git
import org.eclipse.jgit.api.errors.GitAPIException
import org.eclipse.jgit.transport.UsernamePasswordCredentialsProvider
import org.eclipse.microprofile.rest.client.inject.RestClient
import org.kohsuke.github.GHCreateRepositoryBuilder
import org.kohsuke.github.GHRepository
import org.kohsuke.github.GitHubBuilder
import java.io.IOException
import java.io.UncheckedIOException
import java.nio.file.Path
import java.util.Objects.requireNonNull
import javax.enterprise.context.ApplicationScoped
import javax.inject.Inject


@ApplicationScoped
open class GitHubService {

    @Inject
    lateinit var config: GitHubConfig

    @Inject
    @field: RestClient
    internal lateinit var authService: GitHubOAuthService

    @Throws(UncheckedIOException::class)
    open fun createRepository(token: String, repositoryName: String): CreatedRepository {
        check(config.isGitHubEnabled()) { "GitHub is not enabled" }
        require(token.isNotEmpty()) { "token must not be empty." }
        require(repositoryName.isNotEmpty()) { "repositoryName must not be empty." }
        val newlyCreatedRepo: GHRepository
        try {
            val gitHub = GitHubBuilder().withOAuthToken(token).build()
            val repositoryBuilder: GHCreateRepositoryBuilder = gitHub.createRepository(repositoryName)
            newlyCreatedRepo = repositoryBuilder
                    .description("Generated by code.quarkus.io")
                    .create()
        } catch (e: IOException) {
            throw UncheckedIOException(String.format("Could not create GitHub repository named '%s'", repositoryName), e)
        }

        return CreatedRepository(newlyCreatedRepo.ownerName, newlyCreatedRepo.httpTransportUrl)
    }

    open fun push(ownerName: String, token: String, httpTransportUrl: String, path: Path) {
        check(config.isGitHubEnabled()) { "GitHub is not enabled" }
        require(token.isNotEmpty()) { "token must not be empty." }
        require(httpTransportUrl.isNotEmpty()) { "httpTransportUrl must not be empty." }
        require(ownerName.isNotEmpty()) { "ownerName must not be empty." }
        requireNonNull(path, "path must not be null.")

        try {
            Git.init().setDirectory(path.toFile()).call().use { repo ->
                repo.add().addFilepattern(".").call()
                repo.commit().setMessage("Initial commit")
                        .setAuthor("quarkusio", "no-reply@quarkus.io")
                        .setCommitter("quarkusio", "no-reply@quarkus.io")
                        .setSign(false)
                        .call()

                val pushCommand = repo.push()
                pushCommand.remote = httpTransportUrl
                pushCommand.setCredentialsProvider(UsernamePasswordCredentialsProvider(ownerName, token))
                pushCommand.call()
            }
        } catch (e: GitAPIException) {
            throw IllegalStateException("An error occurred while pushing to the git repo", e)
        }

    }

    open fun fetchAccessToken(code: String, state: String): TokenResponse {
        check(config.isGitHubEnabled()) { "GitHub is not enabled" }
        val response = authService.getAccessToken(TokenParameter(config.clientId, config.clientSecret, code, state))
        return TokenResponse(response.getFirst("access_token"), response.getFirst("scope"), response.getFirst("token_type"))
    }
}