## Stage 1 : build with maven builder image
FROM quay.io/quarkus/centos-quarkus-maven:20.1.0-java11 AS build
COPY pom.xml /usr/src/app/
RUN cd /usr/src/app/ && mvn verify clean --fail-never
COPY src /usr/src/app/src
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
RUN cd /usr/src/app/ && mvn clean package

## Stage 2 : create the docker final image
FROM mcr.microsoft.com/playwright:focal
ARG JAVA_PACKAGE=openjdk-11-jre-headless
ARG RUN_JAVA_VERSION=1.3.8

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' QUARKUS_LOCAL_REPO=/tmp/.m2 PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

RUN  apt-get update \
    && apt-get install -y curl ${JAVA_PACKAGE} ca-certificates \
    && apt-get update \
    && mkdir /deployments \
    && chown 1001 /deployments \
    && chmod "g+rwX" /deployments \
    && chown 1001:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 1001 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh \
    && mkdir /.cache \
    && chown 1001:root /.cache \
    && chmod "g+rwX" /.cache

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dfile.encoding=UTF-8"

COPY --from=build --chown=1001 usr/src/app/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=1001 usr/src/app/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=1001 usr/src/app/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=1001 usr/src/app/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
