## Stage 1 : build with maven builder image
FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.2-java17 AS build
ARG MAVEN_BUILD_EXTRA_ARGS=
RUN echo "$MAVEN_BUILD_EXTRA_ARGS"
COPY pom.xml /usr/src/app/
RUN cd /usr/src/app/ && mvn verify clean --fail-never
COPY src /usr/src/app/src
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
RUN cd /usr/src/app/ && mvn clean package -DskipTests $MAVEN_BUILD_EXTRA_ARGS

## Stage 2 : create the docker final image
FROM mcr.microsoft.com/playwright:focal

ARG JAVA_PACKAGE=openjdk-17-jre-headless
ARG MAVEN_EXTRA_ARGS=
RUN echo "$MAVEN_EXTRA_ARGS"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' QUARKUS_LOCAL_REPO=/tmp/.m2 PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

RUN  apt-get update \
    && apt-get install -y curl ${JAVA_PACKAGE} ca-certificates \
    && apt-get update \
    && mkdir /.cache \
    && chown 185:root /.cache \
    && chmod "g+rwX" /.cache

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 usr/src/app/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 usr/src/app/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 usr/src/app/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 usr/src/app/target/quarkus-app/quarkus/ /deployments/quarkus/


EXPOSE 8080
USER 185

ENV AB_JOLOKIA_OFF=""
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dfile.encoding=UTF-8 $MAVEN_EXTRA_ARGS"

ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT java $JAVA_OPTS -jar $JAVA_APP_JAR